import sqlalchemy as sa

#### DB CONNECTION

# ENGINE_URL = sa.engine.url.URL(
#     "postgresql",
#     username="postgres",
#     password="Lin3@r1in3!431",
#     host="linearline.dedicated.co.za",
#     port=5432,
#     database="gauteng",
# )

# ENGINE = sa.create_engine(
#     ENGINE_URL
# )

ENGINE_URL = sa.engine.url.URL(
    "postgresql",
    username="postgres",
    password="Lin3@r1in3!431",
    host="localhost",
    port=5432,
    database="gauteng",
)

ENGINE = sa.create_engine(
    ENGINE_URL
)

OUTPUT_FILE = r"~\Desktop\Temp\rsa_traffic_counts\TEMP_E_COUNT_"

FILES_COMPLETE = r"~\Desktop\Temp\rsa_traffic_counts\RSA_FILES_COMPLETE_localhost.csv"

PATH = r"~\Desktop\Temp\rsa_traffic_counts"

PROBLEM_FILES = r"~\Desktop\Temp\rsa_traffic_counts\RSA_COUNT_PROBLEM_FILES.csv"

DATA_COLUMN_NAMES = [
    "site_id",
    "header_id",
    '"year"',
    "start_datetime",
    "end_datetime",
    "duration_min",
    "direction",
    "forward_direction_code",
    "lane_number",
    "speedbin0",
    "speedbin1",
    "speedbin2",
    "speedbin3",
    "speedbin4",
    "speedbin5",
    "speedbin6",
    "speedbin7",
    "speedbin8",
    "speedbin9",
    "speedbin10",
    "sum_of_heavy_vehicle_speeds",
    "short_heavy_vehicles",
    "medium_heavy_vehicles",
    "long_heavy_vehicles",
    "rear_to_rear_headway_shorter_than_2_seconds",
    "rear_to_rear_headways_shorter_than_programmed_time",
    "total_light_vehicles_type21",
    "total_heavy_vehicles_type21",
    "total_vehicles_type21",
    "unknown_vehicle_error_class",
    "motorcycle",
    "light_motor_vehicles",
    "light_motor_vehicles_towing",
    "heavy_vehicle",
    "two_axle_busses",
    "two_axle_6_tyre_single_units",
    "busses_with_3_or_4_axles",
    "two_axle_6_tyre_single_unit_with_light_trailer_4_axles_max",
    "three_axle_single_unit_including_single_axle_light_trailer",
    "four_or_less_axle_including_a_single_trailer",
    "buses_with_5_or_more_axles",
    "three_axle_single_unit_and_light_trailer_more_than_4_axles",
    "five_axle_single_trailer",
    "six_axle_single_trailer",
    "five_or_less_axle_multi_trailer",
    "six_axle_multi_trailer",
    "seven_axle_multi_trailer",
    "eight_or_more_axle_multi_trailer",
    "total_light_vehicles_type30",
    "total_heavy_vehicles_type30",
    "total_vehicles_type30",
    "number_of_error_vehicles",
    "total_free_flowing_light_vehicles",
    "total_following_light_vehicles",
    "total_free_flowing_heavy_vehicles",
    "total_following_heavy_vehicles",
    "sum_of_inverse_of_speeds_for_free_flowing_lights",
    "sum_of_inverse_of_speeds_for_following_lights",
    "sum_of_inverse_of_speeds_for_free_flowing_heavies",
    "sum_of_inverse_of_speeds_for_following_heavies",
    "sum_of_speeds_for_free_flowing_lights",
    "sum_of_speeds_for_following_lights",
    "sum_of_speeds_for_free_flowing_heavies",
    "sum_of_speeds_for_following_heavies",
    "sum_of_squared_speeds_of_free_flowing_lights",
    "sum_of_squared_speeds_for_following_lights",
    "sum_of_squared_speeds_of_free_flowing_heavies",
    "sum_of_squared_speeds_for_following_heavies",
    "physical_lane_number",
    "forward_1_or_reverse_code_2",
    "vehicle_category",
    "vehicle_class_code_primary_scheme",
    "vehicle_class_code_secondary_scheme",
    "vehicle_speed",
    "vehicle_length",
    "site_occupancy_time_in_milliseconds",
    "chassis_height_code",
    "vehicle_following_code",
    "vehicle_tag_code",
    "trailer_count",
    "axle_count",
    "bumper_to_1st_axle_spacing",
    "sub_data_type_code_axle_spacing",
    "number_of_axles_spacings_counted",
    "axle_spacing_1_between_individual_axles_cm",
    "axle_spacing_2_between_individual_axles_cm",
    "axle_spacing_3_between_individual_axles_cm",
    "axle_spacing_4_between_individual_axles_cm",
    "axle_spacing_5_between_individual_axles_cm",
    "axle_spacing_6_between_individual_axles_cm",
    "axle_spacing_7_between_individual_axles_cm",
    "axle_spacing_8_between_individual_axles_cm",
]

HEADER_COLUMN_NAMES = [
    "header_id",
    "site_id",
    "station_name",
    "x",
    "y",
    "start_datetime",
    "end_datetime",
    "number_of_lanes",
    "type_21_count_interval_minutes",
    "type_21_programmable_rear_to_rear_headway_bin",
    "type_21_program_id",
    "speedbin1",
    "speedbin2",
    "speedbin3",
    "speedbin4",
    "speedbin5",
    "speedbin6",
    "speedbin7",
    "speedbin8",
    "speedbin9",
    "speedbin10",
    "type_10_vehicle_classification_scheme_primary",
    "type_10_vehicle_classification_scheme_secondary",
    "type_10_maximum_gap_milliseconds",
    "type_10_maximum_differential_speed",
    "type_30_summary_interval_minutes",
    "type_30_vehicle_classification_scheme",
    "type_70_summary_interval_minutes",
    "type_70_vehicle_classification_scheme",
    "type_70_maximum_gap_milliseconds",
    "type_70_maximum_differential_speed",
    "type_70_error_bin_code",
    "instrumentation_description",
    "document_url",
    "date_processed",
    "growth_rate_use",
    "total_light_positive_direction",
    "total_light_negative_direction",
    "total_light_vehicles",
    "total_heavy_positive_direction",
    "total_heavy_negative_direction",
    "total_heavy_vehicles",
    "total_short_heavy_positive_direction",
    "total_short_heavy_negative_direction",
    "total_short_heavy_vehicles",
    "total_medium_heavy_positive_direction",
    "total_medium_heavy_negative_direction",
    "total_medium_heavy_vehicles",
    "total_long_heavy_positive_direction",
    "total_long_heavy_negative_direction",
    "total_long_heavy_vehicles",
    "total_vehicles_positive_direction",
    "total_vehicles_negative_direction",
    "total_vehicles",
    "average_speed_positive_direction",
    "average_speed_negative_direction",
    "average_speed",
    "average_speed_light_vehicles_positive_direction",
    "average_speed_light_vehicles_negative_direction",
    "average_speed_light_vehicles",
    "average_speed_heavy_vehicles_positive_direction",
    "average_speed_heavy_vehicles_negative_direction",
    "average_speed_heavy_vehicles",
    "truck_split_positive_direction",
    "truck_split_negative_direction",
    "truck_split_total",
    "estimated_axles_per_truck_positive_direction",
    "estimated_axles_per_truck_negative_direction",
    "estimated_axles_per_truck_total",
    "percentage_speeding_positive_direction",
    "percentage_speeding_negative_direction",
    "percentage_speeding_total",
    "vehicles_with_rear_to_rear_headway_less_than_2sec_positive_dire",
    "vehicles_with_rear_to_rear_headway_less_than_2sec_negative_dire",
    "vehicles_with_rear_to_rear_headway_less_than_2sec_total",
    "estimated_e80_positive_direction",
    "estimated_e80_negative_direction",
    "estimated_e80_on_road",
    "adt_positive_direction",
    "adt_negative_direction",
    "adt_total",
    "adtt_positive_direction",
    "adtt_negative_direction",
    "adtt_total",
    "highest_volume_per_hour_positive_direciton",
    "highest_volume_per_hour_negative_direciton",
    "highest_volume_per_hour_total",
    "15th_highest_volume_per_hour_positive_direction",
    "15th_highest_volume_per_hour_negative_direction",
    "15th_highest_volume_per_hour_total",
    "30th_highest_volume_per_hour_positive_direction",
    "30th_highest_volume_per_hour_negative_direction",
    "30th_highest_volume_per_hour_total",
    "15th_percentile_speed_positive_direction",
    "15th_percentile_speed_negative_direction",
    "15th_percentile_speed_total",
    "85th_percentile_speed_positive_direction",
    "85th_percentile_speed_negative_direction",
    "85th_percentile_speed_total",
    "year",
]
