from pandas import DataFrame
from pandas.testing import assert_frame_equal
import wim

def wim_test():

    header_ids = ['bba9b8bf-9db6-4970-95d3-80f72393af99']

    EXPECTED_RESULT = DataFrame({
        "header_id": header_ids[0] ,
        "egrl_percent": 0 ,
        "egrw_percent": 0 ,
        "mean_equivalent_axle_mass": 0 ,
        "mean_equivalent_axle_mass_positive_direction": 0 ,
        "mean_equivalent_axle_mass_negative_direction": 0 ,
        "mean_axle_spacing": 0 ,
        "mean_axle_spacing_positive_direction": 0 ,
        "mean_axle_spacing_negative_direction": 0 ,
        "e80_per_axle": 0 ,
        "e80_per_axle_positive_direction": 0 ,
        "e80_per_axle_negative_direction": 0 ,
        "olhv": 0 ,
        "olhv_positive_direction": 0 ,
        "olhv_negative_direction": 0 ,
        "olhv_percent": 0 ,
        "olhv_percent_positive_direction": 0 ,
        "olhv_percent_negative_direction": 0 ,
        "tonnage_generated": 0 ,
        "tonnage_generated_positive_direction": 0 ,
        "tonnage_generated_negative_direction": 0 ,
        "olton": 0 ,
        "olton_positive_direction": 0 ,
        "olton_negative_direction": 0 ,
        "olton_percent": 0 ,
        "olton_percent_positive_direction": 0 ,
        "olton_percent_negative_direction": 0 ,
        "ole80": 0 ,
        "ole80_positive_direction": 0 ,
        "ole80_negative_direction": 0 ,
        "ole80_percent": 0 ,
        "ole80_percent_positive_direction": 0 ,
        "ole80_percent_negative_direction": 0 ,
        "xe80": 0 ,
        "xe80_positive_direction": 0 ,
        "xe80_negative_direction": 0 ,
        "xe80_percent": 0 ,
        "xe80_percent_positive_direction": 0 ,
        "xe80_percent_negative_direction": 0 ,
        "e80_per_day": 0 ,
        "e80_per_day_positive_direction": 0 ,
        "e80_per_day_negative_direction": 0 ,
        "e80_per_heavy_vehicle": 0 ,
        "e80_per_heavy_vehicle_positive_direction": 0 ,
        "e80_per_heavy_vehicle_negative_direction": 0 ,
        "worst_steering_single_axle_cnt": 0 ,
        "worst_steering_single_axle_olhv_perc": 0 ,
        "worst_steering_single_axle_tonperhv": 0 ,
        "worst_steering_double_axle_cnt": 0 ,
        "worst_steering_double_axle_olhv_perc": 0 ,
        "worst_steering_double_axle_tonperhv": 0 ,
        "worst_non_steering_single_axle_cnt": 0 ,
        "worst_non_steering_single_axle_olhv_perc": 0 ,
        "worst_non_steering_single_axle_tonperhv": 0 ,
        "worst_non_steering_double_axle_cnt": 0 ,
        "worst_non_steering_double_axle_olhv_perc": 0 ,
        "worst_non_steering_double_axle_tonperhv": 0 ,
        "worst_triple_axle_cnt": 0 ,
        "worst_triple_axle_olhv_perc": 0 ,
        "worst_triple_axle_tonperhv": 0 ,
        "bridge_formula_cnt": 0 ,
        "bridge_formula_olhv_perc": 0 ,
        "bridge_formula_tonperhv": 0 ,
        "gross_formula_cnt": 0 ,
        "gross_formula_olhv_perc": 0 ,
        "gross_formula_tonperhv": 0 ,
        "total_avg_cnt": 0 ,
        "total_avg_olhv_perc": 0 ,
        "total_avg_tonperhv": 0 ,
        "worst_steering_single_axle_cnt_positive_direciton": 0 ,
        "worst_steering_single_axle_olhv_perc_positive_direciton": 0 ,
        "worst_steering_single_axle_tonperhv_positive_direciton": 0 ,
        "worst_steering_double_axle_cnt_positive_direciton": 0 ,
        "worst_steering_double_axle_olhv_perc_positive_direciton": 0 ,
        "worst_steering_double_axle_tonperhv_positive_direciton": 0 ,
        "worst_non_steering_single_axle_cnt_positive_direciton": 0 ,
        "worst_non_steering_single_axle_olhv_perc_positive_direciton": 0 ,
        "worst_non_steering_single_axle_tonperhv_positive_direciton": 0 ,
        "worst_non_steering_double_axle_cnt_positive_direciton": 0 ,
        "worst_non_steering_double_axle_olhv_perc_positive_direciton": 0 ,
        "worst_non_steering_double_axle_tonperhv_positive_direciton": 0 ,
        "worst_triple_axle_cnt_positive_direciton": 0 ,
        "worst_triple_axle_olhv_perc_positive_direciton": 0 ,
        "worst_triple_axle_tonperhv_positive_direciton": 0 ,
        "bridge_formula_cnt_positive_direciton": 0 ,
        "bridge_formula_olhv_perc_positive_direciton": 0 ,
        "bridge_formula_tonperhv_positive_direciton": 0 ,
        "gross_formula_cnt_positive_direciton": 0 ,
        "gross_formula_olhv_perc_positive_direciton": 0 ,
        "gross_formula_tonperhv_positive_direciton": 0 ,
        "total_avg_cnt_positive_direciton": 0 ,
        "total_avg_olhv_perc_positive_direciton": 0 ,
        "total_avg_tonperhv_positive_direciton": 0 ,
        "worst_steering_single_axle_cnt_negative_direciton": 0 ,
        "worst_steering_single_axle_olhv_perc_negative_direciton": 0 ,
        "worst_steering_single_axle_tonperhv_negative_direciton": 0 ,
        "worst_steering_double_axle_cnt_negative_direciton": 0 ,
        "worst_steering_double_axle_olhv_perc_negative_direciton": 0 ,
        "worst_steering_double_axle_tonperhv_negative_direciton": 0 ,
        "worst_non_steering_single_axle_cnt_negative_direciton": 0 ,
        "worst_non_steering_single_axle_olhv_perc_negative_direciton": 0 ,
        "worst_non_steering_single_axle_tonperhv_negative_direciton": 0 ,
        "worst_non_steering_double_axle_cnt_negative_direciton": 0 ,
        "worst_non_steering_double_axle_olhv_perc_negative_direciton": 0 ,
        "worst_non_steering_double_axle_tonperhv_negative_direciton": 0 ,
        "worst_triple_axle_cnt_negative_direciton": 0 ,
        "worst_triple_axle_olhv_perc_negative_direciton": 0 ,
        "worst_triple_axle_tonperhv_negative_direciton": 0 ,
        "bridge_formula_cnt_negative_direciton": 0 ,
        "bridge_formula_olhv_perc_negative_direciton": 0 ,
        "bridge_formula_tonperhv_negative_direciton": 0 ,
        "gross_formula_cnt_negative_direciton": 0 ,
        "gross_formula_olhv_perc_negative_direciton": 0 ,
        "gross_formula_tonperhv_negative_direciton": 0 ,
        "total_avg_cnt_negative_direciton": 0 ,
        "total_avg_olhv_perc_negative_direciton": 0 ,
        "total_avg_tonperhv_negative_direciton": 0 ,
        "egrl_percent_positive_direction": 0 ,
        "egrl_percent_negative_direction": 0 ,
        "egrw_percent_positive_direction": 0 ,
        "egrw_percent_negative_direction": 0 ,
        "num_weighed": 0 ,
        "num_weighed_positive_direction": 0 ,
        "num_weighed_negative_direction": 0,
        "total_vehicles_cls_4tot": 882,
        "weighed_vehicles_cls_4tot": 0,
        "perc_truck_dist_cls_4tot": 0,
        "total_axles_cls_4tot": 0,
        "axles_over9t_cls_4tot": 0,
        "total_mass_cls_4tot": 0,
        "cnt_mass_over9t_cls_4tot": 0,
        "eal_pervehicle_cls_4tot": 0,
        "total_eal_cls_4tot": 0,
        "total_eal_over9t_cls_4tot": 0,
        "total_vehicles_cls_5tot": 14272,
        "weighed_vehicles_cls_5tot": 0,
        "perc_truck_dist_cls_5tot": 0,
        "total_axles_cls_5tot": 0,
        "axles_over9t_cls_5tot": 0,
        "total_mass_cls_5tot": 0,
        "cnt_mass_over9t_cls_5tot": 0,
        "eal_pervehicle_cls_5tot": 0,
        "total_eal_cls_5tot": 0,
        "total_eal_over9t_cls_5tot": 0,
        "total_vehicles_cls_6tot": 456,
        "weighed_vehicles_cls_6tot": 0,
        "perc_truck_dist_cls_6tot": 0,
        "total_axles_cls_6tot": 0,
        "axles_over9t_cls_6tot": 0,
        "total_mass_cls_6tot": 0,
        "cnt_mass_over9t_cls_6tot": 0,
        "eal_pervehicle_cls_6tot": 0,
        "total_eal_cls_6tot": 0,
        "total_eal_over9t_cls_6tot": 0,
        "total_vehicles_cls_7tot": 14,
        "weighed_vehicles_cls_7tot": 0,
        "perc_truck_dist_cls_7tot": 0,
        "total_axles_cls_7tot": 0,
        "axles_over9t_cls_7tot": 0,
        "total_mass_cls_7tot": 0,
        "cnt_mass_over9t_cls_7tot": 0,
        "eal_pervehicle_cls_7tot": 0,
        "total_eal_cls_7tot": 0,
        "total_eal_over9t_cls_7tot": 0,
        "total_vehicles_cls_8tot": 2957,
        "weighed_vehicles_cls_8tot": 0,
        "perc_truck_dist_cls_8tot": 0,
        "total_axles_cls_8tot": 0,
        "axles_over9t_cls_8tot": 0,
        "total_mass_cls_8tot": 0,
        "cnt_mass_over9t_cls_8tot": 0,
        "eal_pervehicle_cls_8tot": 0,
        "total_eal_cls_8tot": 0,
        "total_eal_over9t_cls_8tot": 0,
        "total_vehicles_cls_9tot": 1701,
        "weighed_vehicles_cls_9tot": 0,
        "perc_truck_dist_cls_9tot": 0,
        "total_axles_cls_9tot": 0,
        "axles_over9t_cls_9tot": 0,
        "total_mass_cls_9tot": 0,
        "cnt_mass_over9t_cls_9tot": 0,
        "eal_pervehicle_cls_9tot": 0,
        "total_eal_cls_9tot": 0,
        "total_eal_over9t_cls_9tot": 0,
        "total_vehicles_cls_10tot": 14,
        "weighed_vehicles_cls_10tot": 0,
        "perc_truck_dist_cls_10tot": 0,
        "total_axles_cls_10tot": 0,
        "axles_over9t_cls_10tot": 0,
        "total_mass_cls_10tot": 0,
        "cnt_mass_over9t_cls_10tot": 0,
        "eal_pervehicle_cls_10tot": 0,
        "total_eal_cls_10tot": 0,
        "total_eal_over9t_cls_10tot": 0,
        "total_vehicles_cls_11tot": 100,
        "weighed_vehicles_cls_11tot": 0,
        "perc_truck_dist_cls_11tot": 0,
        "total_axles_cls_11tot": 0,
        "axles_over9t_cls_11tot": 0,
        "total_mass_cls_11tot": 0,
        "cnt_mass_over9t_cls_11tot": 0,
        "eal_pervehicle_cls_11tot": 0,
        "total_eal_cls_11tot": 0,
        "total_eal_over9t_cls_11tot": 0,
        "total_vehicles_cls_12tot": 2075,
        "weighed_vehicles_cls_12tot": 0,
        "perc_truck_dist_cls_12tot": 0,
        "total_axles_cls_12tot": 0,
        "axles_over9t_cls_12tot": 0,
        "total_mass_cls_12tot": 0,
        "cnt_mass_over9t_cls_12tot": 0,
        "eal_pervehicle_cls_12tot": 0,
        "total_eal_cls_12tot": 0,
        "total_eal_over9t_cls_12tot": 0,
        "total_vehicles_cls_13tot": 7564,
        "weighed_vehicles_cls_13tot": 0,
        "perc_truck_dist_cls_13tot": 0,
        "total_axles_cls_13tot": 0,
        "axles_over9t_cls_13tot": 0,
        "total_mass_cls_13tot": 0,
        "cnt_mass_over9t_cls_13tot": 0,
        "eal_pervehicle_cls_13tot": 0,
        "total_eal_cls_13tot": 0,
        "total_eal_over9t_cls_13tot": 0,
        "total_vehicles_cls_14tot": 68,
        "weighed_vehicles_cls_14tot": 0,
        "perc_truck_dist_cls_14tot": 0,
        "total_axles_cls_14tot": 0,
        "axles_over9t_cls_14tot": 0,
        "total_mass_cls_14tot": 0,
        "cnt_mass_over9t_cls_14tot": 0,
        "eal_pervehicle_cls_14tot": 0,
        "total_eal_cls_14tot": 0,
        "total_eal_over9t_cls_14tot": 0,
        "total_vehicles_cls_15tot": 148,
        "weighed_vehicles_cls_15tot": 0,
        "perc_truck_dist_cls_15tot": 0,
        "total_axles_cls_15tot": 0,
        "axles_over9t_cls_15tot": 0,
        "total_mass_cls_15tot": 0,
        "cnt_mass_over9t_cls_15tot": 0,
        "eal_pervehicle_cls_15tot": 0,
        "total_eal_cls_15tot": 0,
        "total_eal_over9t_cls_15tot": 0,
        "total_vehicles_cls_16tot": 6931,
        "weighed_vehicles_cls_16tot": 0,
        "perc_truck_dist_cls_16tot": 0,
        "total_axles_cls_16tot": 0,
        "axles_over9t_cls_16tot": 0,
        "total_mass_cls_16tot": 0,
        "cnt_mass_over9t_cls_16tot": 0,
        "eal_pervehicle_cls_16tot": 0,
        "total_eal_cls_16tot": 0,
        "total_eal_over9t_cls_16tot": 0,
        "total_vehicles_cls_17tot": 183,
        "weighed_vehicles_cls_17tot": 0,
        "perc_truck_dist_cls_17tot": 0,
        "total_axles_cls_17tot": 0,
        "axles_over9t_cls_17tot": 0,
        "total_mass_cls_17tot": 0,
        "cnt_mass_over9t_cls_17tot": 0,
        "eal_pervehicle_cls_17tot": 0,
        "total_eal_cls_17tot": 0,
        "total_eal_over9t_cls_17tot": 0,
        "total_vehicles_cls_4p": 0,
        "weighed_vehicles_cls_4p": 0,
        "perc_truck_dist_cls_4p": 0,
        "total_axles_cls_4p": 0,
        "axles_over9t_cls_4p": 0,
        "total_mass_cls_4p": 0,
        "cnt_mass_over9t_cls_4p": 0,
        "eal_pervehicle_cls_4p": 0,
        "total_eal_cls_4p": 0,
        "total_eal_over9t_cls_4p": 0,
        "total_vehicles_cls_5p": 0,
        "weighed_vehicles_cls_5p": 0,
        "perc_truck_dist_cls_5p": 0,
        "total_axles_cls_5p": 0,
        "axles_over9t_cls_5p": 0,
        "total_mass_cls_5p": 0,
        "cnt_mass_over9t_cls_5p": 0,
        "eal_pervehicle_cls_5p": 0,
        "total_eal_cls_5p": 0,
        "total_eal_over9t_cls_5p": 0,
        "total_vehicles_cls_6p": 0,
        "weighed_vehicles_cls_6p": 0,
        "perc_truck_dist_cls_6p": 0,
        "total_axles_cls_6p": 0,
        "axles_over9t_cls_6p": 0,
        "total_mass_cls_6p": 0,
        "cnt_mass_over9t_cls_6p": 0,
        "eal_pervehicle_cls_6p": 0,
        "total_eal_cls_6p": 0,
        "total_eal_over9t_cls_6p": 0,
        "total_vehicles_cls_7p": 0,
        "weighed_vehicles_cls_7p": 0,
        "perc_truck_dist_cls_7p": 0,
        "total_axles_cls_7p": 0,
        "axles_over9t_cls_7p": 0,
        "total_mass_cls_7p": 0,
        "cnt_mass_over9t_cls_7p": 0,
        "eal_pervehicle_cls_7p": 0,
        "total_eal_cls_7p": 0,
        "total_eal_over9t_cls_7p": 0,
        "total_vehicles_cls_8p": 0,
        "weighed_vehicles_cls_8p": 0,
        "perc_truck_dist_cls_8p": 0,
        "total_axles_cls_8p": 0,
        "axles_over9t_cls_8p": 0,
        "total_mass_cls_8p": 0,
        "cnt_mass_over9t_cls_8p": 0,
        "eal_pervehicle_cls_8p": 0,
        "total_eal_cls_8p": 0,
        "total_eal_over9t_cls_8p": 0,
        "total_vehicles_cls_9p": 0,
        "weighed_vehicles_cls_9p": 0,
        "perc_truck_dist_cls_9p": 0,
        "total_axles_cls_9p": 0,
        "axles_over9t_cls_9p": 0,
        "total_mass_cls_9p": 0,
        "cnt_mass_over9t_cls_9p": 0,
        "eal_pervehicle_cls_9p": 0,
        "total_eal_cls_9p": 0,
        "total_eal_over9t_cls_9p": 0,
        "total_vehicles_cls_10p": 0,
        "weighed_vehicles_cls_10p": 0,
        "perc_truck_dist_cls_10p": 0,
        "total_axles_cls_10p": 0,
        "axles_over9t_cls_10p": 0,
        "total_mass_cls_10p": 0,
        "cnt_mass_over9t_cls_10p": 0,
        "eal_pervehicle_cls_10p": 0,
        "total_eal_cls_10p": 0,
        "total_eal_over9t_cls_10p": 0,
        "total_vehicles_cls_11p": 0,
        "weighed_vehicles_cls_11p": 0,
        "perc_truck_dist_cls_11p": 0,
        "total_axles_cls_11p": 0,
        "axles_over9t_cls_11p": 0,
        "total_mass_cls_11p": 0,
        "cnt_mass_over9t_cls_11p": 0,
        "eal_pervehicle_cls_11p": 0,
        "total_eal_cls_11p": 0,
        "total_eal_over9t_cls_11p": 0,
        "total_vehicles_cls_12p": 0,
        "weighed_vehicles_cls_12p": 0,
        "perc_truck_dist_cls_12p": 0,
        "total_axles_cls_12p": 0,
        "axles_over9t_cls_12p": 0,
        "total_mass_cls_12p": 0,
        "cnt_mass_over9t_cls_12p": 0,
        "eal_pervehicle_cls_12p": 0,
        "total_eal_cls_12p": 0,
        "total_eal_over9t_cls_12p": 0,
        "total_vehicles_cls_13p": 0,
        "weighed_vehicles_cls_13p": 0,
        "perc_truck_dist_cls_13p": 0,
        "total_axles_cls_13p": 0,
        "axles_over9t_cls_13p": 0,
        "total_mass_cls_13p": 0,
        "cnt_mass_over9t_cls_13p": 0,
        "eal_pervehicle_cls_13p": 0,
        "total_eal_cls_13p": 0,
        "total_eal_over9t_cls_13p": 0,
        "total_vehicles_cls_14p": 0,
        "weighed_vehicles_cls_14p": 0,
        "perc_truck_dist_cls_14p": 0,
        "total_axles_cls_14p": 0,
        "axles_over9t_cls_14p": 0,
        "total_mass_cls_14p": 0,
        "cnt_mass_over9t_cls_14p": 0,
        "eal_pervehicle_cls_14p": 0,
        "total_eal_cls_14p": 0,
        "total_eal_over9t_cls_14p": 0,
        "total_vehicles_cls_15p": 0,
        "weighed_vehicles_cls_15p": 0,
        "perc_truck_dist_cls_15p": 0,
        "total_axles_cls_15p": 0,
        "axles_over9t_cls_15p": 0,
        "total_mass_cls_15p": 0,
        "cnt_mass_over9t_cls_15p": 0,
        "eal_pervehicle_cls_15p": 0,
        "total_eal_cls_15p": 0,
        "total_eal_over9t_cls_15p": 0,
        "total_vehicles_cls_16p": 0,
        "weighed_vehicles_cls_16p": 0,
        "perc_truck_dist_cls_16p": 0,
        "total_axles_cls_16p": 0,
        "axles_over9t_cls_16p": 0,
        "total_mass_cls_16p": 0,
        "cnt_mass_over9t_cls_16p": 0,
        "eal_pervehicle_cls_16p": 0,
        "total_eal_cls_16p": 0,
        "total_eal_over9t_cls_16p": 0,
        "total_vehicles_cls_17p": 0,
        "weighed_vehicles_cls_17p": 0,
        "perc_truck_dist_cls_17p": 0,
        "total_axles_cls_17p": 0,
        "axles_over9t_cls_17p": 0,
        "total_mass_cls_17p": 0,
        "cnt_mass_over9t_cls_17p": 0,
        "eal_pervehicle_cls_17p": 0,
        "total_eal_cls_17p": 0,
        "total_eal_over9t_cls_17p": 0,
        "total_vehicles_cls_4n": 0,
        "weighed_vehicles_cls_4n": 0,
        "perc_truck_dist_cls_4n": 0,
        "total_axles_cls_4n": 0,
        "axles_over9t_cls_4n": 0,
        "total_mass_cls_4n": 0,
        "cnt_mass_over9t_cls_4n": 0,
        "eal_pervehicle_cls_4n": 0,
        "total_eal_cls_4n": 0,
        "total_eal_over9t_cls_4n": 0,
        "total_vehicles_cls_5n": 0,
        "weighed_vehicles_cls_5n": 0,
        "perc_truck_dist_cls_5n": 0,
        "total_axles_cls_5n": 0,
        "axles_over9t_cls_5n": 0,
        "total_mass_cls_5n": 0,
        "cnt_mass_over9t_cls_5n": 0,
        "eal_pervehicle_cls_5n": 0,
        "total_eal_cls_5n": 0,
        "total_eal_over9t_cls_5n": 0,
        "total_vehicles_cls_6n": 0,
        "weighed_vehicles_cls_6n": 0,
        "perc_truck_dist_cls_6n": 0,
        "total_axles_cls_6n": 0,
        "axles_over9t_cls_6n": 0,
        "total_mass_cls_6n": 0,
        "cnt_mass_over9t_cls_6n": 0,
        "eal_pervehicle_cls_6n": 0,
        "total_eal_cls_6n": 0,
        "total_eal_over9t_cls_6n": 0,
        "total_vehicles_cls_7n": 0,
        "weighed_vehicles_cls_7n": 0,
        "perc_truck_dist_cls_7n": 0,
        "total_axles_cls_7n": 0,
        "axles_over9t_cls_7n": 0,
        "total_mass_cls_7n": 0,
        "cnt_mass_over9t_cls_7n": 0,
        "eal_pervehicle_cls_7n": 0,
        "total_eal_cls_7n": 0,
        "total_eal_over9t_cls_7n": 0,
        "total_vehicles_cls_8n": 0,
        "weighed_vehicles_cls_8n": 0,
        "perc_truck_dist_cls_8n": 0,
        "total_axles_cls_8n": 0,
        "axles_over9t_cls_8n": 0,
        "total_mass_cls_8n": 0,
        "cnt_mass_over9t_cls_8n": 0,
        "eal_pervehicle_cls_8n": 0,
        "total_eal_cls_8n": 0,
        "total_eal_over9t_cls_8n": 0,
        "total_vehicles_cls_9n": 0,
        "weighed_vehicles_cls_9n": 0,
        "perc_truck_dist_cls_9n": 0,
        "total_axles_cls_9n": 0,
        "axles_over9t_cls_9n": 0,
        "total_mass_cls_9n": 0,
        "cnt_mass_over9t_cls_9n": 0,
        "eal_pervehicle_cls_9n": 0,
        "total_eal_cls_9n": 0,
        "total_eal_over9t_cls_9n": 0,
        "total_vehicles_cls_10n": 0,
        "weighed_vehicles_cls_10n": 0,
        "perc_truck_dist_cls_10n": 0,
        "total_axles_cls_10n": 0,
        "axles_over9t_cls_10n": 0,
        "total_mass_cls_10n": 0,
        "cnt_mass_over9t_cls_10n": 0,
        "eal_pervehicle_cls_10n": 0,
        "total_eal_cls_10n": 0,
        "total_eal_over9t_cls_10n": 0,
        "total_vehicles_cls_11n": 0,
        "weighed_vehicles_cls_11n": 0,
        "perc_truck_dist_cls_11n": 0,
        "total_axles_cls_11n": 0,
        "axles_over9t_cls_11n": 0,
        "total_mass_cls_11n": 0,
        "cnt_mass_over9t_cls_11n": 0,
        "eal_pervehicle_cls_11n": 0,
        "total_eal_cls_11n": 0,
        "total_eal_over9t_cls_11n": 0,
        "total_vehicles_cls_12n": 0,
        "weighed_vehicles_cls_12n": 0,
        "perc_truck_dist_cls_12n": 0,
        "total_axles_cls_12n": 0,
        "axles_over9t_cls_12n": 0,
        "total_mass_cls_12n": 0,
        "cnt_mass_over9t_cls_12n": 0,
        "eal_pervehicle_cls_12n": 0,
        "total_eal_cls_12n": 0,
        "total_eal_over9t_cls_12n": 0,
        "total_vehicles_cls_13n": 0,
        "weighed_vehicles_cls_13n": 0,
        "perc_truck_dist_cls_13n": 0,
        "total_axles_cls_13n": 0,
        "axles_over9t_cls_13n": 0,
        "total_mass_cls_13n": 0,
        "cnt_mass_over9t_cls_13n": 0,
        "eal_pervehicle_cls_13n": 0,
        "total_eal_cls_13n": 0,
        "total_eal_over9t_cls_13n": 0,
        "total_vehicles_cls_14n": 0,
        "weighed_vehicles_cls_14n": 0,
        "perc_truck_dist_cls_14n": 0,
        "total_axles_cls_14n": 0,
        "axles_over9t_cls_14n": 0,
        "total_mass_cls_14n": 0,
        "cnt_mass_over9t_cls_14n": 0,
        "eal_pervehicle_cls_14n": 0,
        "total_eal_cls_14n": 0,
        "total_eal_over9t_cls_14n": 0,
        "total_vehicles_cls_15n": 0,
        "weighed_vehicles_cls_15n": 0,
        "perc_truck_dist_cls_15n": 0,
        "total_axles_cls_15n": 0,
        "axles_over9t_cls_15n": 0,
        "total_mass_cls_15n": 0,
        "cnt_mass_over9t_cls_15n": 0,
        "eal_pervehicle_cls_15n": 0,
        "total_eal_cls_15n": 0,
        "total_eal_over9t_cls_15n": 0,
        "total_vehicles_cls_16n": 0,
        "weighed_vehicles_cls_16n": 0,
        "perc_truck_dist_cls_16n": 0,
        "total_axles_cls_16n": 0,
        "axles_over9t_cls_16n": 0,
        "total_mass_cls_16n": 0,
        "cnt_mass_over9t_cls_16n": 0,
        "eal_pervehicle_cls_16n": 0,
        "total_eal_cls_16n": 0,
        "total_eal_over9t_cls_16n": 0,
        "total_vehicles_cls_17n": 0,
        "weighed_vehicles_cls_17n": 0,
        "perc_truck_dist_cls_17n": 0,
        "total_axles_cls_17n": 0,
        "axles_over9t_cls_17n": 0,
        "total_mass_cls_17n": 0,
        "cnt_mass_over9t_cls_17n": 0,
        "eal_pervehicle_cls_17n": 0,
        "total_eal_cls_17n": 0,
        "total_eal_over9t_cls_17n": 0,
    }, index=[0])

    for header_id in header_ids:
        if header_id is None:
            pass
        else:
            WIM = wim.Wim(None, None, None, None, None)
            SELECT_TYPE10_QRY, AXLE_SPACING_SELECT_QRY, WHEEL_MASS_SELECT_QRY = WIM.wim_header_upsert_func1(header_id)
            df, df2, df3 = WIM.wim_header_upsert_func2(
                SELECT_TYPE10_QRY, AXLE_SPACING_SELECT_QRY, WHEEL_MASS_SELECT_QRY)
            if df2 is None or df3 is None:
                print(f"passing {header_id}")
            else:
                print(f'working on {header_id}')
                actual_results = WIM.wim_header_calcs(df, df2, df3)

    assert_frame_equal(EXPECTED_RESULT, actual_results)

if __name__ == '__main__':
    wim_test()